#pragma once

void test_lazy_empty();
void test_lazy_from_array();
void test_lazy_from_sequence();
void test_lazy_with_generator();
void test_lazy_copy();
void test_size_finite();
void test_size_infinite();
void test_lazy_get_finite();
void test_lazy_get_infinite();
void test_lazy_get_out_of_range();
void test_lazy_get_first_finite();
void test_lazy_get_first_infinite();
void test_lazy_get_first_empty();
void test_lazy_get_last_finite();
void test_lazy_get_last_infinite();
void test_lazy_get_last_empty();
void test_lazy_materialized_count_finite();
void test_lazy_materialized_count_infinite();
